---

  - name: Installs and configures Nginx web server. 
    ansible.builtin.apt:
      name: nginx
    
  - name: Updating cache
    ansible.builtin.apt:
      update_cache: yes
    
  - name: Index page
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/index.html