---

  - name: Installs and configures Nginx web server
    ansible.builtin.apt:
      name: nginx
    #for solving big red error activate nginx
  - name: Updating cache
    ansible.builtin.apt:
      update_cache: yes

  - name: Index page.
    ansible.builtin.copy:
      src: index.html
      dest: /var/www/html/index.html
      #########
  - name: Copy default to somewhere
    ansible.builtin.copy:
      src: default
      dest: /etc/nginx/sites-enabled/default
    notify: Restart Nginx
    
  - name: Start nginx unconditionally
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
      