---

  - name: Installs and configures Nginx web server. 
    ansible.builtin.apt:
    name: nginx
    
  - name: Installing Ubuntu Focal 
    ansible.builtin.apt:
    name: Ubuntu 20.04 Focal Fossa
    update_cache: yes
    
  - name: Index page
    ansible.builtin.copy:
    src: index.html
    dest: /var/www/html/index.html

  