---

  - name: Dependencies for Grafana
    ansible.builtin.apt: 
      name:
        - adduser 
        - libfontconfig1
  
  - name: Download Grafana
    ansible.builtin.get_url:
      url: https://dl.grafana.com/oss/release/grafana_7.2.1_amd64.deb
      dest: /opt/grafana_7.2.1_amd64.deb 
      

  - name: Install Grafana
    ansible.builtin.apt:
      deb: /opt/grafana_7.2.1_amd64.deb 

  #- name: Reconfigure Grafana
  #  ansible.builtin.template:
   #   src: main.json
  #    dest: /etc/grafana/main.json
  #  notify: Restart Grafana

  - name: Start Grafana
    ansible.builtin.service:
      name: grafana-server
      state: started
      enabled: yes