---

  - name: Install "uwsgi" package
    ansible.builtin.apt:
      name: uwsgi

  - name: Install "uwsgi-plugin-python3" package
    ansible.builtin.apt:
      name: uwsgi-plugin-python3
      
  - name: Run agama
    ansible.builtin.user:
      user: agama
      
  - name: Copy agama.ini
    ansible.builtin.copy:
      src: agama.ini
      dest: /etc/uwsgi/apps-enabled/agama.ini
    
        