---
#step 1:
  - name: Install "uwsgi" package
    ansible.builtin.apt:
      name: uwsgi

  - name: Install "uwsgi-plugin-python3" package
    ansible.builtin.apt:
      name: uwsgi-plugin-python3
#step 2:    
  - name: Copy agama.ini
    ansible.builtin.copy:
      src: agama.ini
      dest: /etc/uwsgi/apps-enabled/agama.ini
#step 3:
  - name: uWSGI service is started unconditionally
    ansible.builtin.service:
      name: uwsgi
      state: started
      enaled: yes
#step 4: not finished
  - name: uWSGI is restarted automatically
    ansible.builtin.service:
      state: restarted
    when: 
#next step: adding role - done

#you can start task 3 but remember that sqlite is not finished,  also STEP 4        