---

  - name: Collect information about all VMs
    hosts: all
    tasks:
      - setup:

  - name: Init
    hosts: all
    roles:
      - init
    become: yes
  
  - name: Database server
    hosts: db_servers
    roles:
      - mysql    
    become: yes

  - name: DNS server
    hosts: dns_servers
    roles:
      - bind    
    become: yes

  - name: Web server
    hosts: web_servers
    roles:
      - agama
      - uwsgi
      - nginx
    become: yes

  - name: Node Exporter
    hosts: node_exporters
    roles:
      - node_exporter
    become: yes

  - name: Configure Prometheus
    hosts: prometheus
    roles:
      - prometheus
      - nginx
    become: yes
    
- name: Install MySQL exporter
  hosts: db_servers
  become: yes
  roles:
    - mysql_exporter
  tags: mysql

- name: Install Bind exporter
  hosts: dns_servers
  become: yes
  roles:
    - bind_exporter


- name: Install Nginx exporter
  hosts: prometheus
  become: yes
  roles:
    - nginx_exporter
  tags: nginx_exporter
 

- name: Install Grafana
  hosts: grafana
  become: yes
  roles:
    - grafana
  tags: grafana
    