---

  - name: Bind9 exporter
    ansible.builtin.apt:
      name: prometheus-bind-exporter

  - name: Start Bind9 exporter
    ansible.builtin.service:
      name: prometheus-bind-exporter
      state: started
      enabled: yes